'use strict';

const { Vendor } = require('../models');

let options = {};
if (process.env.NODE_ENV === 'production') {
  options.schema = process.env.SCHEMA;  // define your schema in options object
}

module.exports = {
  up: async (queryInterface, Sequelize) => {
    const vendors = [
      {
        id: 1,
        name: 'Blue Plate Catering',
        category: 'Catering',
        contactName: 'Sarah Johnson',
        contactEmail: 'sarah@blueplatecatering.com',
        contactPhone: '(312) 421-6666',
        website: 'https://www.blueplatecatering.com',
        address: '1061 W Van Buren St',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60607',
        latitude: 41.876436,
        longitude: -87.654321,
        priceAmount: 45.00,
        priceCurrency: 'USD',
        priceNote: 'Per person, minimum 25 guests',
        description: 'Blue Plate Catering is a premier catering company in Chicago, providing exceptional food and service for corporate events, weddings, and social gatherings. Our farm-to-table approach focuses on locally-sourced ingredients and sustainable practices.',
        notes: 'Specializes in sustainable and locally-sourced ingredients. Offers gluten-free and vegan options.',
        status: 'confirmed',
        rating: 5,
        tags: JSON.stringify(['Farm-to-Table', 'Sustainable', 'Corporate Events', 'Weddings']),
        createdAt: new Date('2024-01-15'),
        updatedAt: new Date('2024-03-22')
      },
      {
        id: 2,
        name: 'George Street Photo & Video',
        category: 'Photography',
        contactName: 'Michael Roberts',
        contactEmail: 'bookings@georgestreetphoto.com',
        contactPhone: '(866) 831-4103',
        website: 'https://www.georgestreetphoto.com',
        address: '219 W Chicago Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60654',
        latitude: 41.896823,
        longitude: -87.636242,
        priceAmount: 2500.00,
        priceCurrency: 'USD',
        priceNote: 'Starting package, 8 hours of coverage',
        description: 'George Street Photo & Video is a national wedding photography company with a team of professional photographers and videographers. We provide customizable packages to capture your special day with a blend of photojournalistic, traditional, and artistic styles.',
        notes: 'Clients receive online gallery access and can order prints directly.',
        status: 'booked',
        rating: 4,
        tags: JSON.stringify(['Wedding', 'Portrait', 'Photojournalistic', 'Video']),
        createdAt: new Date('2024-02-03'),
        updatedAt: new Date('2024-04-10')
      },
      {
        id: 3,
        name: 'The Langham Chicago',
        category: 'Venue',
        contactName: 'Jennifer Williams',
        contactEmail: 'events.chicago@langhamhotels.com',
        contactPhone: '(312) 923-9988',
        website: 'https://www.langhamhotels.com/en/the-langham/chicago/',
        address: '330 N Wabash Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60611',
        latitude: 41.888411,
        longitude: -87.627456,
        priceAmount: 8500.00,
        priceCurrency: 'USD',
        priceNote: 'Venue rental, food & beverage minimums apply',
        description: 'The Langham Chicago offers elegant event spaces with stunning views of the Chicago River and skyline. Our dedicated team provides exceptional service for weddings, corporate events, and social gatherings in a luxurious setting.',
        notes: 'Five-star hotel with on-site catering, audiovisual services, and luxury accommodations for guests.',
        status: 'considering',
        rating: 5,
        tags: JSON.stringify(['Luxury', 'Downtown', 'River View', 'Hotel']),
        createdAt: new Date('2024-01-05'),
        updatedAt: new Date('2024-03-15')
      },
      {
        id: 4,
        name: 'Toast & Jam DJs',
        category: 'Entertainment',
        contactName: 'Rachel Lyons',
        contactEmail: 'info@toastandjam.com',
        contactPhone: '(773) 687-8833',
        website: 'https://www.toastandjam.com',
        address: '2617 W Fletcher St',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60618',
        latitude: 41.938446,
        longitude: -87.690459,
        priceAmount: 1800.00,
        priceCurrency: 'USD',
        priceNote: 'For 5-hour reception, includes consultation and planning',
        description: 'Toast & Jam is a female-fronted DJ collective specializing in weddings and private events. We take a personalized approach to music curation, working closely with clients to create the perfect soundtrack for their special day.',
        notes: 'Known for their personalized approach and ability to read the crowd.',
        status: 'contacted',
        rating: 5,
        tags: JSON.stringify(['DJ', 'Wedding', 'Event', 'Female-Owned']),
        createdAt: new Date('2024-02-12'),
        updatedAt: new Date('2024-04-05')
      },
      {
        id: 5,
        name: 'HMR Designs',
        category: 'Decor',
        contactName: 'Daniel Martinez',
        contactEmail: 'info@hmrdesigns.com',
        contactPhone: '(773) 782-0800',
        website: 'https://www.hmrdesigns.com',
        address: '3200 N Kedzie Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60618',
        latitude: 41.940083,
        longitude: -87.707506,
        priceAmount: 5000.00,
        priceCurrency: 'USD',
        priceNote: 'Starting price, varies by event scope',
        description: 'HMR Designs is a full-service event design company specializing in floral arrangements, custom fabrication, and comprehensive event decor. With over 50 years of experience, we transform spaces into unforgettable environments for weddings, galas, and corporate events.',
        notes: 'Has a 20,000 square foot design studio. Can handle very large and complex installations.',
        status: 'confirmed',
        rating: 5,
        tags: JSON.stringify(['Floral', 'Custom', 'Luxury', 'Full-Service']),
        createdAt: new Date('2024-01-20'),
        updatedAt: new Date('2024-03-25')
      },
      {
        id: 6,
        name: 'Windy City Limousine',
        category: 'Transportation',
        contactName: 'Robert Thompson',
        contactEmail: 'info@windycitylimos.com',
        contactPhone: '(866) 949-4639',
        website: 'https://www.windycitylimos.com',
        address: '2300 S Archer Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60616',
        latitude: 41.851149,
        longitude: -87.636798,
        priceAmount: 800.00,
        priceCurrency: 'USD',
        priceNote: 'For 4-hour minimum, varies by vehicle',
        description: 'Windy City Limousine provides luxury transportation services for weddings, corporate events, and airport transfers. Our fleet includes sedans, SUVs, stretch limousines, and buses to accommodate groups of all sizes.',
        notes: 'Very reliable service. Offers real-time vehicle tracking.',
        status: 'booked',
        rating: 4,
        tags: JSON.stringify(['Limousine', 'Shuttle', 'Airport', 'Luxury']),
        createdAt: new Date('2024-02-05'),
        updatedAt: new Date('2024-04-02')
      },
      {
        id: 7,
        name: 'Fleur Inc',
        category: 'Florist',
        contactName: 'Kelly Marie Thompson',
        contactEmail: 'hello@fleurinc.com',
        contactPhone: '(312) 494-0940',
        website: 'https://www.fleurinc.com',
        address: '715 N Franklin St',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60654',
        latitude: 41.896229,
        longitude: -87.635647,
        priceAmount: 3500.00,
        priceCurrency: 'USD',
        priceNote: 'Average wedding package, varies by season and flower selection',
        description: 'Fleur Inc is a boutique floral design studio creating custom arrangements for weddings and events. Our aesthetic combines natural elements with artistic design for romantic, garden-inspired creations that tell your unique story.',
        notes: 'Specializes in locally-grown, seasonal flowers when possible.',
        status: 'considering',
        rating: 5,
        tags: JSON.stringify(['Boutique', 'Artistic', 'Sustainable', 'Weddings']),
        createdAt: new Date('2024-01-25'),
        updatedAt: new Date('2024-03-30')
      },
      {
        id: 8,
        name: 'West Town Bakery',
        category: 'Bakery',
        contactName: 'Chris Teixeira',
        contactEmail: 'events@westtownbakery.com',
        contactPhone: '(773) 916-6576',
        website: 'https://www.westtownbakery.com',
        address: '1916 W Chicago Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60622',
        latitude: 41.896220,
        longitude: -87.676008,
        priceAmount: 750.00,
        priceCurrency: 'USD',
        priceNote: 'Starting price for wedding cakes, $8 per slice average',
        description: 'West Town Bakery is a sustainable bakery creating custom cakes and desserts for weddings and special events. We use local, organic ingredients and offer vegan and gluten-free options without compromising on taste or design.',
        notes: 'LGBTQ-owned business. All packaging is compostable or recyclable.',
        status: 'contacted',
        rating: 4,
        tags: JSON.stringify(['Custom Cakes', 'Sustainable', 'Vegan Options', 'Organic']),
        createdAt: new Date('2024-02-15'),
        updatedAt: new Date('2024-04-08')
      },
      {
        id: 9,
        name: 'LK Events',
        category: 'Event Planning',
        contactName: 'Lauren Knuepfer Rozum',
        contactEmail: 'info@lkevents.com',
        contactPhone: '(773) 727-4851',
        website: 'https://www.lkevents.com',
        address: '1165 N Clark St',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60610',
        latitude: 41.903333,
        longitude: -87.631704,
        priceAmount: 6500.00,
        priceCurrency: 'USD',
        priceNote: 'Full planning package, partial planning available at lower rates',
        description: 'LK Events is a full-service event planning company specializing in luxury weddings and social events. We manage every detail from vendor selection to day-of coordination, ensuring a seamless and stress-free experience for our clients.',
        notes: 'Has excellent industry connections with top vendors in Chicago.',
        status: 'confirmed',
        rating: 5,
        tags: JSON.stringify(['Full-Service', 'Luxury', 'Weddings', 'Corporate']),
        createdAt: new Date('2024-01-10'),
        updatedAt: new Date('2024-03-20')
      },
      {
        id: 10,
        name: 'AVFX Chicago',
        category: 'Audio/Visual',
        contactName: 'Brian Johnson',
        contactEmail: 'chicago@avfx.com',
        contactPhone: '(312) 229-4800',
        website: 'https://www.avfx.com',
        address: '401 N Michigan Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60611',
        latitude: 41.889905,
        longitude: -87.624343,
        priceAmount: 3200.00,
        priceCurrency: 'USD',
        priceNote: 'Base package for corporate events, custom quotes available',
        description: 'AVFX Chicago provides professional audio, video, and lighting solutions for corporate events, conferences, and galas. Our technical expertise and state-of-the-art equipment ensure flawless execution for presentations, performances, and immersive experiences.',
        notes: 'Experienced with major Chicago venues and their specific requirements.',
        status: 'contacted',
        rating: 4,
        tags: JSON.stringify(['Corporate', 'Conference', 'Technical', 'Production']),
        createdAt: new Date('2024-02-20'),
        updatedAt: new Date('2024-04-15')
      },
      {
        id: 11,
        name: 'Monterrey Security',
        category: 'Security',
        contactName: 'Juan Gaytan',
        contactEmail: 'events@monterreysecurity.com',
        contactPhone: '(312) 953-8211',
        website: 'https://www.monterreysecurity.com',
        address: '2232 S Blue Island Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60608',
        latitude: 41.851030,
        longitude: -87.670383,
        priceAmount: 45.00,
        priceCurrency: 'USD',
        priceNote: 'Per hour per guard, 4-hour minimum',
        description: 'Monterrey Security provides professional security services for events of all sizes, from intimate gatherings to large-scale festivals. Our trained personnel ensure guest safety while maintaining a hospitable atmosphere for your event.',
        notes: 'Security provider for major Chicago venues and events. Staff is trained in emergency response.',
        status: 'booked',
        rating: 4,
        tags: JSON.stringify(['Event Security', 'Professional', 'Crowd Management', 'Certified']),
        createdAt: new Date('2024-01-30'),
        updatedAt: new Date('2024-03-28')
      },
      {
        id: 12,
        name: 'ServiceMaster Restoration',
        category: 'Cleaning',
        contactName: 'David Wilson',
        contactEmail: 'chicago@servicemaster.com',
        contactPhone: '(773) 376-1110',
        website: 'https://www.servicemasterrestore.com',
        address: '2912 N Central Park Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60618',
        latitude: 41.934654,
        longitude: -87.718487,
        priceAmount: 850.00,
        priceCurrency: 'USD',
        priceNote: 'Starting price for post-event cleanup, varies by venue size',
        description: 'ServiceMaster provides professional post-event cleaning services for venues and event spaces. Our experienced team ensures spaces are thoroughly cleaned and restored to their original condition efficiently after events of any size.',
        notes: 'Available 24/7 for emergency cleanup. Uses eco-friendly cleaning products.',
        status: 'considering',
        rating: 4,
        tags: JSON.stringify(['Post-Event', 'Professional', 'Commercial', 'Eco-Friendly']),
        createdAt: new Date('2024-02-25'),
        updatedAt: new Date('2024-04-18')
      },
      {
        id: 13,
        name: 'Fig Catering',
        category: 'Catering',
        contactName: 'Justin Hall',
        contactEmail: 'info@figcatering.com',
        contactPhone: '(312) 265-1200',
        website: 'https://www.figcatering.com',
        address: '1850 S Blue Island Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60608',
        latitude: 41.856872,
        longitude: -87.661508,
        priceAmount: 65.00,
        priceCurrency: 'USD',
        priceNote: 'Per person, 30 guest minimum',
        description: 'Fig Catering specializes in seasonal, made-from-scratch cuisine for weddings and events. Our food is locally sourced when possible, and we offer full-service catering with customizable menus to suit your taste and dietary needs.',
        notes: 'Excellent vegetarian and vegan options. Known for attentive service.',
        status: 'contacted',
        rating: 5,
        tags: JSON.stringify(['Seasonal', 'Local', 'Custom Menus', 'Full-Service']),
        createdAt: new Date('2024-01-18'),
        updatedAt: new Date('2024-03-24')
      },
      {
        id: 14,
        name: 'Greenhouse Loft Photography',
        category: 'Photography',
        contactName: 'Jessica McCall',
        contactEmail: 'hello@greenhouseloft.com',
        contactPhone: '(312) 402-7991',
        website: 'https://www.greenhouseevents.net/photo',
        address: '2545 W Diversey Ave',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60647',
        latitude: 41.932048,
        longitude: -87.689505,
        priceAmount: 3200.00,
        priceCurrency: 'USD',
        priceNote: 'Full-day wedding coverage, second shooter included',
        description: 'Greenhouse Loft Photography offers natural, documentary-style wedding and event photography. Our team captures authentic moments with an artistic eye, delivering timeless images that tell your unique story.',
        notes: 'Specializes in sustainable weddings and events. Uses natural light effectively.',
        status: 'booked',
        rating: 5,
        tags: JSON.stringify(['Documentary', 'Sustainable', 'Natural Light', 'Artistic']),
        createdAt: new Date('2024-02-08'),
        updatedAt: new Date('2024-04-12')
      },
      {
        id: 15,
        name: 'Chicago History Museum',
        category: 'Venue',
        contactName: 'Emily Reynolds',
        contactEmail: 'events@chicagohistory.org',
        contactPhone: '(312) 799-2254',
        website: 'https://www.chicagohistory.org/events',
        address: '1601 N Clark St',
        city: 'Chicago',
        state: 'IL',
        zipCode: '60614',
        latitude: 41.911973,
        longitude: -87.631674,
        priceAmount: 6500.00,
        priceCurrency: 'USD',
        priceNote: 'Venue rental fee, food and beverage minimum additional',
        description: 'The Chicago History Museum offers elegant, historic spaces for weddings and events. Located in Lincoln Park, our venue features a grand ballroom with classic architecture, a garden plaza for outdoor ceremonies, and unique exhibits that showcase Chicago\'s rich history.',
        notes: 'Preferred caterer list available. Includes museum access for guests during events.',
        status: 'considering',
        rating: 4,
        tags: JSON.stringify(['Historic', 'Museum', 'Lincoln Park', 'Elegant']),
        createdAt: new Date('2024-01-08'),
        updatedAt: new Date('2024-03-18')
      }
    ];

    // Insert the vendors
    await queryInterface.bulkInsert('Vendors', vendors, options);
  },

  down: async (queryInterface, Sequelize) => {
    options.tableName = 'Vendors';
    // Delete the vendors
    await queryInterface.bulkDelete('Vendors', null, options);
  }
};